### ISSUE TITLE
Prune finished branches

### ISSUE THREAD

**Issue by skmorgane** [weecology/Metabarcoding#17]
So we're not wondering which branches are active, we should work on deleting branches that have finished their mission

**Comment by bleds22e** [comment]
I always delete them from my local repo (?) once they've been merged. Can you delete them before the PR has been merged?

**Comment by bleds22e** [comment]
Ok, based on the fact that the little red trash can in greyed out next to the open PRs, I'm going to answer my own question with a "no"
