### ISSUE TITLE
Metabarcoding Database Creation

### ISSUE THREAD

**Issue by skmorgane** [weecology/Metabarcoding#4]
- [x] Combine ITS Blast and NoBlast files

- [x] Move ITS taxon data from sequence reads file to new ITS OTU-taxon-linker file

- [x] Split voucher and poop sequence read data into separate files for TrnL

- [x] Split voucher and poop sequence read data into separate files for ITS

- [x] Turn TrnL poop sequence reads data into flat file with no zeros

- [x] Turn ITS poop sequence reads data into flat file with no zeros

- [x] Turn TrnL voucher sequence reads data into flat file with no zeros

- [x] Turn ITS voucher sequence reads data into flat file with no zeros

- [x] Reformat the TRnL OTU-Taxon-Linker file to split out taxonomic data into columns and remove * from the non-SEED entries

**Comment by bleds22e** [comment]
We should decide if we want our data points in number of reads or proportion of reads. I think proportions are more useful, but if we decide to use them, we should make sure we keep copies of the csv files they sent us so we have pure read numbers as well.

**Comment by bleds22e** [comment]
All of this is in PR #9
